stages:
  - build
  - test

default:
  tags:
    - podman

alma8-build:
  image: almalinux:8-minimal
  stage: build
  #when: manual

  before_script:
    - microdnf install -y epel-release
    - microdnf install -y --enablerepo=powertools make netcdf-fortran-devel.x86_64 eccodes-devel.x86_64 netcdf.x86_64

  script:
    - export FC=gfortran
    - export LIBRARY_PATH=/usr/lib64
    - export CPATH=/usr/include:/usr/lib64/gfortran/modules
    - make -j -C src -f makefile_gfortran
  artifacts:
    paths:
      - ./src/FLEXPART

options-test:
  image: almalinux:8-minimal
  stage: test
  #when: manual
  needs:
    - alma8-build

  before_script:
    - microdnf install -y epel-release
    - microdnf install -y --enablerepo=powertools make netcdf-fortran-devel.x86_64 eccodes-devel.x86_64 netcdf.x86_64
  script:
    - ulimit -s unlimited
    - bash ./tests/run_default_options_test.sh
