stages:
  - build
  - test
  - compare

default:
  tags:
    - podman

alma8-build:
  image: harbor.wolke.img.univie.ac.at/flexpart/almalinux8:latest
  stage: build

  script:
    - export FC=gfortran
    - export LIBRARY_PATH=/usr/lib64:/usr/local/lib64
    - export CPATH=/usr/include:/usr/local/include:/usr/lib64/gfortran/modules
    - make -j -C src -f makefile_gfortran
  artifacts:
    paths:
      - ./src/FLEXPART

options-test:
  image: harbor.wolke.img.univie.ac.at/flexpart/almalinux8:latest
  stage: test
  needs:
    - alma8-build

  script:
    - ulimit -s unlimited
    - bash ./tests/run_default_options_test.sh
  
openmp-simulation:
  image: harbor.wolke.img.univie.ac.at/flexpart/almalinux8:latest
  stage: test
  needs:
    - alma8-build

  script:
    - ulimit -s unlimited
    - bash ./tests/run_openmp_test.sh
  
  artifacts:
    when: on_success
    paths:
      - ./tests/output_omp1
      - ./tests/output_omp32
    expire_in: 5 mins

etex-simulation:
  image: harbor.wolke.img.univie.ac.at/flexpart/almalinux8:latest
  stage: test
  when: manual
  needs:
    - alma8-build

  script:
    - ulimit -s unlimited
    - bash ./tests/run_etex_test.sh

  artifacts:
    when: on_success
    paths:
      - ./tests/output_etex
    expire_in: 10 mins

openmp-test:
  image: harbor.wolke.img.univie.ac.at/flexpart/postprocessing:py39
  stage: compare
  needs:
    - job: openmp-simulation
      artifacts: true
  script:
    - cd ./tests/
    - python3 ./openmp_test.py

etex-test:
  image: harbor.wolke.img.univie.ac.at/flexpart/postprocessing:py39
  stage: compare
  needs:
    - job: etex-simulation
      artifacts: true
  script:
    - cd ./tests/
    - python3 ./etex_test.py
  artifacts:
    when: on_success
    paths:
      - ./tests/etex_test.txt
    expire_in: never